[package]
name = "flat"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = 'z' 

[dependencies]
clap = { version = "4.5.20" }
deno_core = "0.314.1"
quick-js = "0.4.1"
rand = "0.8.5"
